### ISSUE TITLE
[C01] 3.1.12 채팅목록 

### ISSUE THREAD

**Issue by zeroyouth** [nurimeansworld/strawberry_market#13]
## 페이지 설명
**3.1.12 채팅 목록**

- 채팅 목록과 채팅방은 마크업 구현 및 스타일 적용만 진행합니다.
- 현재 대화가 진행 중인 채팅 목록이 표시됩니다.
- 내가 읽지 않은 메시지가 있는 채팅방인 경우 프로필 사진 좌측 상단에 작은 원으로 표시됩니다.

## 리스트
- ~~html 완료~~
- css 90% 완료
  - [x] 사용자가 읽지 않은 메세지, 가상요소로 사진 좌측에 원 표시해주기
- **js 작업**
  - [x] 채팅 리스트를 눌렀을 때 채팅방으로 넘어가게 하기 #14 
  - [x] 상단 nav js #5 
  - [x] 하단 메뉴 nav js 

## TODO::

**Comment by zeroyouth** [comment]
![span처리](https://user-images.githubusercontent.com/86909942/152368822-b17e965c-4af7-4123-b44b-cd6c6f583681.JPG)

- 실시간 댓글에 span 처리했음

**Comment by zeroyouth** [comment]
![C01](https://user-images.githubusercontent.com/86909942/152451647-c8961fa2-8903-42d0-9471-adcc8476e16f.gif)

- 채팅 리스트를 눌렀을 때 채팅방으로 넘어가게 하기 https://github.com/nurimeansworld/strawberry_market/issues/14
