### ISSUE TITLE
[P03] 3.1.7 팔로워, 팔로잉 목록(2차)

### ISSUE THREAD

**Issue by nurimeansworld** [nurimeansworld/strawberry_market#32]
## 요구사항
- 내가 팔로우 한 사용자일 경우 취소 버튼이, 내가 팔로우 하지 않은 사용자일 경우에는 팔로우 버튼이 표시됩니다.
## 완료
- 사용자 프로필 페이지에서 팔로워 및 팔로잉 수를 클릭하면 나타나는 페이지입니다.
- 목록은 사용자 프로필 사진, 이름, 계정 ID, 팔로우(또는 취소) 버튼으로 구성됩니다.
- 단, 팔로우 기능은 구현하지 않습니다. 버튼의 변화만 구현하세요.

***
## P03 팔로우, 팔로워
- [x] 팔로우, 팔로워 페이지 정보에 따라 분기처리 -> 별도 페이지 생성
- [x] 팔로잉 계정 정보
  - [x] 사진, 이름, 소개글, 계정 URL
  - [x] 팔로잉 계정 반복문으로 li 동적으로 추가
  - [x] 팔로우여부 확인해 button 다르게 출력
- [x] 팔로워 계정 정보
  - [x] 사진, 이름, 소개글, 계정 URL
  - [x] 팔로잉 계정 반복문으로 li 동적으로 추가
  - [x] 팔로우여부 확인해 button 다르게 출력
- [ ] ~소개글 말줄임표 줄넘김 확인~ -> 샘플에 되어있지 않길래 우선순위 후순으로

**Comment by nurimeansworld** [comment]
(상황 공유)
- 팔로워 필로잉 분기처리가 힘들어 P03_1.html 추가하여 index.html에도 추가해두었습니다.
  - (파일명 수정하면 git에서 다른 파일로 인식해 이전 수정사항도 단계별로 보기 힘들어서 안예쁘지만 이렇게 추가했습니다..^_ㅜ)
  - P03.html - 팔로잉
  - P03_1.html - 팔로워
- api 연동 완료
- 각 페이지별로 아래 2가지 남았습니다.
  - 계정정보 리스트로 동적으로 추가
  - 계정과의 팔로잉 여부 확인하여 팔로우/취소 버튼 출력

**Comment by nurimeansworld** [comment]
위의 작업 모두 완료.
## TODO:
- [ ] accountName 동적으로 받아오기
- [ ] 사용자 프로필 클릭시 계정 정보 받아와 이동 링크 설정

**Comment by nurimeansworld** [comment]
요구된 기능 모두 구현하여 이슈 close 합니다 🙏 이후의 수정사항은 별도 이슈로 생성하여 관리 예정입니다.
